### ISSUE TITLE
Svelte boilerplate

### ISSUE THREAD

**Issue by Hassancxpm** [HubSpot/cms-vue-boilerplate#4]
Hi, 

I used to do a PR with a svelte version last week. 

I'm sorry, think I PR on my own repo, I didn't mean to PR this repo. Thank you to remove it and thank you for your work.

You can find my Svelte boilerplate version here: https://github.com/Hassancxpm/cms-svelte-boilerplate

Please fell free to close this issue.

So sorry 😞 😢

**Comment by miketalley** [comment]
No worries @Hassancxpm! Glad to see you're getting some use out of the repo! Cheers!
